### PR TITLE
Add support for the new Cards API

### PR DESCRIPTION
**Pull request by mark-adams**
Documentation available at

- https://ecosystem.atlassian.net/wiki/display/HIPDEV/Extending+the+HipChat+Apps
- https://ecosystem.atlassian.net/wiki/display/HIPDEV/HipChat+Cards

This API is officially still in Beta but is quickly being adopted by add-on makers.

### CODE REVIEW

**Comment by tbruyelle** [comment]
This is awesome thank you, I'm gonna test it right now. Some apps I created will love to post cards in our hipchat.

**Comment by tbruyelle** [comment]
Unfortunatly I didn't manage to post a card to our instance. I always get the same error : 

```json
"error": {
    "code": 400,
    "description": "Value {value!r} is not of type {expected_type!r}",
    "expected_type": [
      {
        "type": "null"
      },

```

With the following code : 

```go
n := &hipchat.NotificationRequest{
       Message: "Hello from cards",
       Card: &hipchat.Card{
         URL:         "http://i0.kym-cdn.com/photos/images/newsfeed/000/131/786/tumblr_ljkeuyjp1a1qafrh6.gif",
         Title:       "Test Cards",
         Icon:        hipchat.Icon{URL: "http://i0.kym-cdn.com/photos/images/newsfeed/000/131/786/tumblr_ljkeuyjp1a1qafrh6.gif"},
         Description: hipchat.CardDescription{Format: "html", Value: "Hello from the new <strong>Cards API</strong>"},
         Date:        uint32(time.Now().Unix()),
       Activity: hipchat.Activity{
          Icon: "http://i0.kym-cdn.com/photos/images/newsfeed/000/131/786/tumblr_ljkeuyjp1a1qafrh6.gif",
           HTML: json.RawMessage(`{"boo":"plop"}`),
         },
       },
     }
     resp, err := c.Room.Notification(roomId, n)
```

- I enabled Hipchat Connect in my instance Group Admin.
- If I remove the `Card` field from the `NotificationRequest, it works, the message appears in the room.
- I tried to remove all `Card` fields one by one and test, but I still have the error.

I suspect something wrong in the `Card` format, but I didn't manage to find what. If you can help me that would be great.

Thanks in advance.

**Comment by mark-adams** [comment]
Yea, I figured it out. My optional fields on `Card` needed to be pointers so that omitempty would exclude them properly.

This is a minimal example of making a card API call (use your own token and room_id, of course):
```
c := NewClient(token)

r := &NotificationRequest{
	Message: "This is a test",
	Card: &Card{
		ID:    "Hello",
		Style: CardStyleApplication,
		Title: "This is a test",
		Description: CardDescription{
			Value: "It works!",
		},
	},
}

resp, err := c.Room.Notification("2150887", r)
```

**Comment by tbruyelle** [comment]
Yeah it works now without the `Activity` field, but as soon as I add it again, I get the same error. 

Actually, `Activity` should be defined like that : 

```go
// Activity represents an activity that occurred
type Activity struct {
  Icon *Icon  `json:"icon,omitempty"`
  HTML string `json:"html,omitempty"` // Not sure why you used json.RawMessage here
}
```
I noticed also other errors/misses (maybe due to API change?) : 

- `AttributeValue.Style` is missing.
- `Card.Images` is not defined in the documentation
- `Card.Thumbnail` is missing (it replaces Card.Images?)
- `AttributeValue.Icon` should be of type `Icon`, not `string`.

I would like to push the fixes to that PR, but I'm not sure it's possible without a write access to your fork.

**Comment by tbruyelle** [comment]
I finaly merged your PR with some fixes, could you tell me why you used `json.RawMessage` for `Activity.HTML` ? (I kept that)

I also added you as a collobarator to the project :)

**Comment by mark-adams** [comment]
@tbruyelle So... the json.RawMessage thing had something to do with Go automatically escaping the HTML content (if I recall correctly). I actually wrote that code about ~3 months ago so I'm a bit hazy. I'll play around with it and see if I can reproduce the issue.

**Comment by tbruyelle** [comment]
So if it was a failed experiment, maybe we should replace it with `string`, that won't solve the issue but it's simpler to use. wdyt?

**Pull request merged**
