### PR TITLE
Add Go 1.8 to test matrix for Travis.

### PR DESCRIPTION
**Pull request by asedge**

### CODE REVIEW

**Comment by asedge** [comment]
I guess this PR might get larger unless you have no interest in supporting Go 1.8.

**Comment by asedge** [comment]
As far as I can tell this works fine with Go 1.8. Tests pass and I was able to use it to pull my rooms via the API.

**Comment by tbruyelle** [comment]
Is it fixable ?

**Comment by asedge** [comment]
@tbruyelle I think so!  It looks like there's just a typo here: https://github.com/tbruyelle/hipchat-go/blob/master/hipchat/room.go#L185

**Comment by asedge** [comment]
@tbruyelle I wanted to add another room notification test that exercises the change to the `Thumbnail` struct and noticed something else odd.  The `Card` struct uses a pointer to `Icon` the `Thumbail` attribute, here: https://github.com/tbruyelle/hipchat-go/blob/master/hipchat/room.go#L96.  So it's never actually using that `Thumbnail` struct.  Am I missing something here?

**Comment by tbruyelle** [comment]
Merged, thank you!

**Comment by asedge** [comment]
👍

**Pull request merged**
