### PR TITLE
Build against 1.5 and tip add makefile

### PR DESCRIPTION
**Pull request by ojongerius**

### CODE REVIEW

**Comment by tbruyelle** [comment]
Wow it's been a while since I hadn't read a Makefile ^^. Thanks for the contribution.

Is their a reason why you didn't add a 'all' target to run everything ? It may be useful before a push, instead of running `test` then `testcase` then `vet`. 
A `go lint` check may also be useful what do you think ?

**Comment by ojongerius** [comment]
:smile: I've added an alias, as you suggested. I've added a go lint check too (which is not meant to be enforcing, but can be helpful).

I've removed support for 1.1 and 1.2 so we can 'go get' golint.

**Comment by ojongerius** [comment]
Had to remove 1.3 to make 'go vet' pass. What do you think?

**Comment by tbruyelle** [comment]
Nice, maybe there is not need of `make test` in the travis file if you already run `make all` before ?

**Comment by ojongerius** [comment]
Right. Done!

**Comment by tbruyelle** [comment]
It seems you forgot to push your modification. Doesn't matter I fixed the travis file and merged your PR as 9bb033a9a5c309e9e1a06c4bcc52331c5d0cbd8e

Thanks !

**Comment by ojongerius** [comment]
:bow:

**Pull request closed without merging**
